# Generated by Django 4.0.1 on 2022-09-20 09:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='APA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('APA_file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='FYP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('FYP_file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('pro_pic', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles')),
                ('bio', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('school', models.CharField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('DZO', 'Dzongkhag'), ('HSS', 'Higher Secondary School'), ('MSS', 'Middle Secondary School'), ('LSS', 'Lower Secondary School'), ('PS', 'Primary School'), ('ECR', 'Extended Classroom'), ('NFE', 'Non-formal Education'), ('Muenseling', 'Muenseling Institute')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super admin')),
                ('is_school', models.BooleanField(default=False, verbose_name='school admin')),
                ('is_dzongkhag', models.BooleanField(default=False, verbose_name='dzongkhag admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tozay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('standard', models.CharField(blank=True, choices=[('PP', 'PP'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=30)),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, null=True)),
                ('stream', models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science'), ('General', 'General')], max_length=100, null=True)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('DoB', models.DateField(blank=True)),
                ('CID', models.CharField(blank=True, max_length=11, unique=True)),
                ('student_code', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=50, null=True)),
                ('gewog', models.CharField(blank=True, max_length=50, null=True)),
                ('dzongkhag', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_CID', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_CID', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.profile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school')),
            ],
        ),
        migrations.CreateModel(
            name='TopperOfYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('standard', models.CharField(blank=True, choices=[('PP', 'PP'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=30)),
                ('stream', models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science'), ('General', 'General')], max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.profile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('standard', models.CharField(blank=True, choices=[('PP', 'PP'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=30)),
                ('section', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, null=True)),
                ('stream', models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science'), ('General', 'General')], max_length=100, null=True)),
                ('total_boys', models.IntegerField(blank=True, null=True)),
                ('total_girls', models.IntegerField(blank=True, null=True)),
                ('total_students', models.IntegerField(blank=True, null=True)),
                ('total_boarder_boys', models.IntegerField(blank=True, null=True)),
                ('total_boarder_girls', models.IntegerField(blank=True, null=True)),
                ('total_boarder_students', models.IntegerField(blank=True, null=True)),
                ('total_dayscholar_boys', models.IntegerField(blank=True, null=True)),
                ('total_dayscholar_girls', models.IntegerField(blank=True, null=True)),
                ('total_dayscholar_students', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.profile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_name', to='SherigApp.school')),
                ('school_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_cat', to='SherigApp.school')),
            ],
        ),
        migrations.CreateModel(
            name='StaffOnleave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_leave', models.CharField(blank=True, choices=[('ML', 'ML'), ('LTT', 'LTT'), ('EoL', 'EoL'), ('Superannuation', 'Superannuation'), ('Resignation', 'Resignation')], max_length=30, null=True)),
                ('office_order', models.CharField(blank=True, max_length=250, null=True)),
                ('Start_date', models.DateField(blank=True, null=True)),
                ('End_date', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('School', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Employee_ID', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True)),
                ('CID', models.CharField(blank=True, max_length=11, unique=True)),
                ('category', models.CharField(blank=True, choices=[('Administration', 'Administration'), ('Teaching Staff', 'Teaching Staff'), ('Non Teaching Staff', 'Non Teaching Staff'), ('Supporting Staff', 'Supporting Staff')], max_length=30)),
                ('position_title', models.CharField(blank=True, max_length=50)),
                ('position_level', models.CharField(blank=True, max_length=10)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('appointment_date', models.DateField(blank=True)),
                ('joining_date_of_present_school', models.DateField(blank=True)),
                ('transfered_from', models.CharField(blank=True, max_length=50)),
                ('Employment_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Contract', 'Contract')], max_length=30)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('qualification', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='staff')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.profile')),
                ('School', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CapitalActivites',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity', models.CharField(blank=True, max_length=300, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('contractor_name', models.CharField(blank=True, max_length=50)),
                ('contractor_mobile_number', models.CharField(blank=True, max_length=12)),
                ('engineer_name', models.CharField(blank=True, max_length=50)),
                ('engineer_mobile_number', models.CharField(blank=True, max_length=12)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.profile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school')),
            ],
        ),
    ]
