# Generated by Django 4.0.1 on 2022-09-20 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfrastructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('total_number', models.IntegerField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('bought_year', models.IntegerField(blank=True, null=True)),
                ('renovation_year', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.profile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school')),
            ],
        ),
    ]
