# Generated by Django 4.0.1 on 2022-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0002_schoolinfrastructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('DZO', 'Dzongkhag'), ('HSS', 'Higher Secondary School'), ('MSS', 'Middle Secondary School'), ('LSS', 'Lower Secondary School'), ('PS', 'Primary School'), ('Muenseling', 'Muenseling Institute')], max_length=20),
        ),
    ]
