# Generated by Django 4.0.1 on 2022-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0003_alter_customuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_school',
            field=models.BooleanField(default=False, verbose_name='school admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super User'),
        ),
    ]
