# Generated by Django 4.0.1 on 2022-11-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0003_alter_school_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='school_cat',
        ),
        migrations.AddField(
            model_name='students',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_cat', to='SherigApp.school'),
        ),
    ]
