# Generated by Django 4.0.1 on 2022-11-07 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0004_remove_students_school_cat_students_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SherigApp.school'),
        ),
    ]
