# Generated by Django 4.0.1 on 2022-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0005_alter_students_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
