# Generated by Django 4.0.1 on 2022-11-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0006_alter_students_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetail',
            name='school_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
