# Generated by Django 4.0.1 on 2022-11-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0007_staffdetail_school_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
