# Generated by Django 4.0.1 on 2022-11-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0008_profile_school_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_category',
        ),
    ]
