# Generated by Django 4.1.6 on 2023-02-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherigApp', '0009_remove_profile_school_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='standard',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Braille', 'Braille')], max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='stream',
            field=models.CharField(blank=True, choices=[('EVS', 'EVS'), ('Economics', 'Economics'), ('Agri', 'Agri'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science'), ('General', 'General')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topperofyear',
            name='standard',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Braille', 'Braille')], max_length=30),
        ),
        migrations.AlterField(
            model_name='topperofyear',
            name='stream',
            field=models.CharField(blank=True, choices=[('EVS', 'EVS'), ('Economics', 'Economics'), ('Agri', 'Agri'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science'), ('General', 'General')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tozay',
            name='standard',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Braille', 'Braille')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tozay',
            name='stream',
            field=models.CharField(blank=True, choices=[('EVS', 'EVS'), ('Economics', 'Economics'), ('Agri', 'Agri'), ('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science'), ('General', 'General')], max_length=100, null=True),
        ),
    ]
